config/routes.rb
Rails.application.routes.draw do
  post 'line_items/increase_quantity' => 'line_items#increase_quantity'
  post 'line_item/decrease_quantity' => 'line_items#decrease_quantity'
  resources :line_items, only: [:create, :destroy]
  resources :categories, :users, :sessions, :orders
  get 'search_suggestions' => 'products#search_suggestions', as: :search_suggestions

  resources :products do
    resources :comments
  end

  get 'cart' => 'carts#show'
  delete 'cart.:id' => 'carts#destroy'

  namespace :admin do
    resources :categories, :users, :products, :orders
  end

  get 'admin' => 'admin/admin#index'
  root 'pages#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :line_items, dependent: :destroy

  enum status: [:"Новый", :"В обработке", :"Выполнен", :"Отменен"]

  validates :user, :status, presence: true

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def index
    @orders = Order.all.order(:status)
  end

  def show
    @line_items = @order.line_items
  end

  def edit
  end

  def update
    if @order.update(order_params)
      flash[:success] = "Статус заказа обновлен"
      redirect_to [:admin, @order]
    else
      render :edit
    end
  end

  def destroy
    @order.destroy
    flash[:success] = "Заказ удален"
    redirect_to admin_orders_url
  end

  private

    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:status)
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user
  before_action :set_order, only: [:show]

  def show
    @line_items = @order.line_items
  end

  def create
    @cart = current_cart
    @order = Order.new
    @order.add_line_items_from_cart(@cart)
    @order.status = :"Новый"
    @order.user = current_user
    if @cart.line_items.empty?
      flash[:alert] = "Корзина пустая, для заказа выберите продукт"
      redirect_to products_path
      return
    end
    if @order.save
      Cart.destroy(session[:cart_id])
      session[:cart_id] = nil
      flash[:success] = "Заказ выполнен!"
      redirect_to root_path
    else
      @cart = current_cart
      flash[:alert] = "Что-то пошло не так, сообщите в поддержку"
      redirect_to :back
    end
  end

  private

    def set_order
      @order = Order.find(params[:id])
    end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= form_for([:admin, @order]) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <% @order.errors.full_messages.each do |message| %>
        <div class="alert alert-danger alert-dismissible fade in" role=alert>
          <button type=button class=close data-dismiss=alert aria-label=Close>
            <span aria-hidden=true>&times;</span>
          </button>
          <%= message %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.select(:status, Order.statuses.to_a.map{ |w| [w[0].humanize, w[0]] }, {}, { class: "form-control" }) %>
  </div>
  <div class="col-xs-8 form-group">
    <%= f.submit class: "btn btn-primary btn-block", value: "Изменить статус" %>
  </div>
<% end %>

app/views/admin/orders/_list_line_items.html.erb
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Продукт</th>
        <th>Количество</th>
        <th>Цена</th>
      </tr>
    </thead>
    <tbody>
      <% @line_items.each do |li| %>
        <tr>
          <td><%= link_to li.product.title, product_path(li.product) %></td>
          <td><%= li.quantity %></td>
          <td><%= number_to_currency(li.product.price, unit: "₴") %></td>
        </tr>
      <% end %>
      <tr>
        <td>Общая сумма:</td>
        <td><%= number_to_currency(order_total_price, unit: "₴") %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/admin/orders/_table_index_each.html.erb
<div class="table-responsive">
  <table class="table table-striped table-hover vertical-align">
    <thead>
      <tr>
        <th>#</th>
        <th>Статус выполнения</th>
        <th>Дата</th>
        <th>Пользователь</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <%= content_tag :tr,
          class: case order.status
          when "Новый"
            "warning"
          when "В обработке"
            "active"
          when "Выполнен"
            "success"
          else "Отменен"
            "danger"
          end do %>
          <td><%= link_to order.id, [:admin, order] %></td>
          <td><%= order.status.humanize %></td>
          <td><%= order.created_at.strftime("%m-%e-%y %H:%M") %></td>
          <td><%= link_to order.user.name, user_path(order.user) %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/orders/edit.html.erb
<h2>Смена статуса заказа</h2>

<%= render 'form' %>
<div class="col-xs-4">
  <%= link_to 'Отмена', admin_orders_path, class: "btn btn-danger btn-block" %>
</div>

app/views/admin/orders/index.html.erb
<h2>Заказы</h2>

<%= render "table_index_each" %>

app/views/admin/orders/show.html.erb
<p>
  <strong>Статус выполнения:</strong>
  <%= @order.status.humanize %>
  <%= link_to 'сменить', edit_admin_order_path(@order) %>
</p>

<p>
  <strong>Пользователь:</strong>
  <%= @order.user.name %>
</p>

<%= render "admin/orders/list_line_items" %>