config/routes.rb
Rails.application.routes.draw do
  post 'line_items/increase_quantity' => 'line_items#increase_quantity'
  post 'line_item/decrease_quantity' => 'line_items#decrease_quantity'
  resources :line_items, only: [:create, :destroy]
  resources :categories, :users, :sessions, :orders
  get 'search_suggestions' => 'products#search_suggestions', as: :search_suggestions

  resources :products do
    resources :comments
  end

  get 'cart' => 'carts#show'
  delete 'cart.:id' => 'carts#destroy'

  namespace :admin do
    resources :categories, :users, :products, :orders
  end

  get 'admin' => 'admin/admin#index'
  root 'pages#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products, dependent: :destroy

  validates :title, presence: true,
                    uniqueness: true
  validates :description, presence: true
  validates :image_url, presence: true

  mount_uploader :image, CategoryUploader
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :check_admin

  def index
    @categories = Category.all.order(:title)
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Категория создана!"
      redirect_to ([:admin, @category])
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      flash[:success] = "Категория обновлена"
      redirect_to ([:admin, @category])
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash[:success] = "Категория удалена"
    redirect_to admin_categories_path
  end

  private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:title, :description, :image)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]

  def index
    @categories = Category.all.order(:created_at)
  end

  def show
  end

  private

    def set_category
      @category = Category.find(params[:id])
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for([:admin, @category]) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <% @category.errors.full_messages.each do |message| %>
        <div class="alert alert-danger alert-dismissible fade in" role=alert>
          <button type=button class=close data-dismiss=alert aria-label=Close>
            <span aria-hidden=true>&times;</span>
          </button>
          <%= message %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, "Название" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description, "Описание" %>
    <%= f.text_area :description, class: "form-control", rows: "4" %>
  </div>
  <div class="form-group">
    <%= f.label :image, "Изображение" %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="col-xs-8 form-group">
    <%= f.submit class: "btn btn-primary btn-block", value: "Отправить" %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<%= render 'form' %>

<div class="col-xs-4">
  <%= link_to 'Отмена', admin_categories_path , class: "btn btn-danger btn-block"%>
</div>

app/views/admin/categories/index.html.erb
<h2>Категории</h2>
<%= link_to 'Новая категория', new_admin_category_path, class: "btn btn-default btn-sm new-item-button" %>

<div class="table-responsive">
  <table class="table table-striped table-hover vertical-align">
    <thead>
      <tr>
        <th>Название</th>
        <th>Фото</th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= link_to category.title, [:admin, category] %></td>
          <td><%= image_tag category.image_url(:small) if category.image? %></td>
          <td>
            <%= link_to edit_admin_category_path(category) do %>
              <span class="glyphicon glyphicon-pencil text-muted" aria-hidden="true"></span>
            <% end %>
          </td>
          <td>
            <%= link_to [:admin, category], method: :delete, data: { confirm: 'Вы уверены?' } do %>
              <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/categories/new.html.erb
<h2>Новая категория</h2>
<%= render 'form' %>
<div class="col-xs-4">
  <%= link_to 'Отмена', admin_categories_path, class: "btn btn-danger btn-block" %>
</div>

app/views/admin/categories/show.html.erb
<div class="col-xs-4">
  <%= image_tag @category.image_url(:middle), class: "img-responsive" if @category.image? %>
</div>
<div class="col-xs-8">
  <h4><%= @category.title %></h4>
  <p class="text-muted"><%= @category.description %></p>
</div>
<div class="col-xs-12">
  <%= link_to 'Редактировать', edit_admin_category_path(@category), class: "btn btn-default pull-right" %>
</div>