config/routes.rb
Rails.application.routes.draw do
  post 'line_items/increase_quantity' => 'line_items#increase_quantity'
  post 'line_item/decrease_quantity' => 'line_items#decrease_quantity'
  resources :line_items, only: [:create, :destroy]
  resources :categories, :users, :sessions, :orders
  get 'search_suggestions' => 'products#search_suggestions', as: :search_suggestions

  resources :products do
    resources :comments
  end

  get 'cart' => 'carts#show'
  delete 'cart.:id' => 'carts#destroy'

  namespace :admin do
    resources :categories, :users, :products, :orders
  end

  get 'admin' => 'admin/admin#index'
  root 'pages#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  before_destroy :ensure_not_referenced

  belongs_to :category
  has_many :line_items, dependent: :destroy
  has_many :comments

  validates :title, presence: true,
                    uniqueness: true
  validates :description, presence: true
  validates :price, presence: true
  validates :image_url, presence: true
  validates :category, presence: true

  mount_uploader :image, ProductUploader

  self.per_page = 3

  private

    def self.search(query)
      where('title LIKE ? OR description LIKE ?', "%#{query}%", "%#{query}%")
    end

    def self.search_for_ajax(query)
      where('title ILIKE ? OR description ILIKE ?', "%#{query}%", "%#{query}%").select(:id, :title)
    end

    def ensure_not_referenced
      if line_items.empty?
        true
      else
        errors.add(:base, "Позиция уже существует.")
        false
      end
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :get_collect_categories, except: [:index, :show, :destroy]
  before_action :check_admin

  def index
    @products = Product.all.order(:title)
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Продукт создан!"
      redirect_to [:admin, @product]
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      flash[:success] = "Продукт обновлен"
      redirect_to [:admin, @product]
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    flash[:success] = "Продукт удален"
    redirect_to admin_products_url
  end

  private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :description, :price, :image, :category_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]

  def index
    @category = Category.where(id: params[:category]).first if params[:category].present?
    @products = if params[:query].present?
                  Product.search(params[:query]).page(params[:page]).order(created_at: "DESC")
                else
                  if @category.present?
                    @category.products.page(params[:page]).order(created_at: "DESC")
                  else
                    Product.page(params[:page]).order(created_at: "DESC")
                  end
                end
  end

  def show
  end

  def search_suggestions
    results = if params[:query].present?
                Product.search_for_ajax(params[:query])
              else
                []
              end
    render json: results
  end

  private

    def set_product
      @product = Product.find(params[:id])
    end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for([:admin, @product]) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <% @product.errors.full_messages.each do |message| %>
        <div class="alert alert-danger alert-dismissible fade in" role=alert>
          <button type=button class=close data-dismiss=alert aria-label=Close>
            <span aria-hidden=true>&times;</span>
          </button>
          <%= message %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, "Название" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description, "Описание" %>
    <%= f.text_area :description, class: "form-control", rows: "4" %>
  </div>
  <div class="form-group">
    <%= f.label :price, "Цена" %>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image_url, "Изображение" %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :category_id, "Категория" %>
    <%= f.collection_select(:category_id, @categoies, :id, :title, {}, class: "form-control") %>
  </div>
  <div class="col-xs-8 form-group">
    <%= f.submit class: "btn btn-primary btn-block", value: "Отправить" %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<%= render 'form' %>

<div class="col-xs-4">
  <%= link_to 'Отмена', admin_products_path, class: "btn btn-danger btn-block" %>
</div>

app/views/admin/products/index.html.erb
<h2>Продукты</h2>
<%= link_to 'Новый продукт', new_admin_product_path, class: "btn btn-default btn-sm new-item-button" %>

<div class="table-responsive">
  <table class="table table-striped table-hover vertical-align">
    <thead>
      <tr>
        <th>Название</th>
        <th>Цена</th>
        <th>Фото</th>
        <th>Категория</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= link_to product.title, [:admin, product] %></td>
          <td><%= number_to_currency(product.price, unit: "₴") %></td>
          <td><%= image_tag product.image_url(:small) if product.image? %></td>
          <td><%= product.category.title %></td>
          <td>
            <%= link_to edit_admin_product_path(product) do %>
              <span class="glyphicon glyphicon-pencil text-muted" aria-hidden="true"></span>
            <% end %>
          </td>
          <td>
            <%= link_to [:admin, product], method: :delete, data: { confirm: 'Вы уверены?' } do %>
              <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/products/new.html.erb
<h2>Новый продукт</h2>

<%= render 'form' %>
<div class="col-xs-4">
  <%= link_to 'Отмена', admin_products_path, class: "btn btn-danger btn-block" %>
</div>

app/views/admin/products/show.html.erb
<div class="col-xs-4">
  <%= image_tag @product.image_url(:middle), class: "img-responsive" if @product.image? %>
</div>
<div class="col-xs-8">
  <h4><%= @product.title %></h4>
  <p><%= link_to @product.category.title, admin_categories_path, class: "text-right" %></p>
  <p class="text-muted"><%= @product.description %></p>
  <h4 class="text-danger text-right"><%= number_to_currency(@product.price, unit: "₴") %></h4>
</div>
<div class="col-xs-12">
  <%= link_to 'Редактировать', edit_admin_product_path(@product), class: "btn btn-default pull-right" %>
</div>