config/routes.rb
Rails.application.routes.draw do
  post 'line_items/increase_quantity' => 'line_items#increase_quantity'
  post 'line_item/decrease_quantity' => 'line_items#decrease_quantity'
  resources :line_items, only: [:create, :destroy]
  resources :categories, :users, :sessions, :orders
  get 'search_suggestions' => 'products#search_suggestions', as: :search_suggestions

  resources :products do
    resources :comments
  end

  get 'cart' => 'carts#show'
  delete 'cart.:id' => 'carts#destroy'

  namespace :admin do
    resources :categories, :users, :products, :orders
  end

  get 'admin' => 'admin/admin#index'
  root 'pages#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  before_destroy :ensure_not_referenced

  belongs_to :category
  has_many :line_items, dependent: :destroy
  has_many :comments

  validates :title, presence: true,
                    uniqueness: true
  validates :description, presence: true
  validates :price, presence: true
  validates :image_url, presence: true
  validates :category, presence: true

  mount_uploader :image, ProductUploader

  self.per_page = 3

  private

    def self.search(query)
      where('title LIKE ? OR description LIKE ?', "%#{query}%", "%#{query}%")
    end

    def self.search_for_ajax(query)
      where('title ILIKE ? OR description ILIKE ?', "%#{query}%", "%#{query}%").select(:id, :title)
    end

    def ensure_not_referenced
      if line_items.empty?
        true
      else
        errors.add(:base, "Позиция уже существует.")
        false
      end
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :get_collect_categories, except: [:index, :show, :destroy]
  before_action :check_admin

  def index
    @products = Product.all.order(:title)
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Продукт создан!"
      redirect_to [:admin, @product]
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      flash[:success] = "Продукт обновлен"
      redirect_to [:admin, @product]
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    flash[:success] = "Продукт удален"
    redirect_to admin_products_url
  end

  private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :description, :price, :image, :category_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]

  def index
    @category = Category.where(id: params[:category]).first if params[:category].present?
    @products = if params[:query].present?
                  Product.search(params[:query]).page(params[:page]).order(created_at: "DESC")
                else
                  if @category.present?
                    @category.products.page(params[:page]).order(created_at: "DESC")
                  else
                    Product.page(params[:page]).order(created_at: "DESC")
                  end
                end
  end

  def show
  end

  def search_suggestions
    results = if params[:query].present?
                Product.search_for_ajax(params[:query])
              else
                []
              end
    render json: results
  end

  private

    def set_product
      @product = Product.find(params[:id])
    end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.erb
<div class="col-sm-6 col-md-4">
  <div class="thumbnail">
    <%= link_to (image_tag product.image_url(:big)), product_path(product), class: "img-responsive" if product.image? %>
    <div class="caption">
      <h3 class="text-center text-muted"><%= link_to product.title, product_path(product) %></h3>
        <h4 class="text-danger text-center"><%= number_to_currency(product.price, unit: "") %> грн</h4>
        <p><%= button_to 'Купить', line_items_path(product_id: product), class: 'btn btn-success btn-block' %></p>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<% if @category.present? %>
  <h2 class="text-warning"><%= @category.title %></h2>
<% else %>
  <h2 class="text-warning">Все продукты</h2>
<% end %>

<%= render @products %>
<div class="paginate">
  <%= will_paginate @products, renderer: BootstrapPagination::Rails %>
</div>

app/views/products/show.html.erb
<div class="col-xs-4">
  <%= image_tag @product.image_url(:middle), class: "img-responsive" if @product.image? %>
</div>
<div class="col-xs-8">
  <h4><%= @product.title %></h4>
  <p><%= link_to @product.category.title, admin_categories_path, class: "text-right" %></p>
  <p class="text-muted"><%= @product.description %></p>
  <h4 class="text-danger text-right"><%= number_to_currency(@product.price, unit: "₴") %></h4>
  <p><%= button_to 'Купить', line_items_path(product_id: @product), class: 'btn btn-success btn-block' %></p>
</div>
<div class="clearfix"></div>
<div class="col-md-12">
  <% if @product.comments.present? %>
    <h4>Комментарии к блюду</h4>
  <% else %>
    <h4>Комментариев еще нет</h4>
  <% end %>
  <ul class="media-list">
    <%= render @product.comments %>
  </ul>
  <%= render "comments/form" %>
</div>